version: '3'

services:
  influxdb:
    image: influxdb
    restart: always
    hostname: influx
    ports:
      - "8086:8086"
    networks:
      - socaNet
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_DB=grafana
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=pingaMax
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=mytoken
      - DOCKER_INFLUXDB_INIT_ORG=org_name
      - DOCKER_INFLUXDB_INIT_BUCKET=my-bucket
    volumes:
      - influxdb_data:/var/lib/influxdb

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    restart: always
    hostname: grafana
    networks:
      - socaNet
    depends_on:
      - influxdb
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource,grafana-worldmap-panel,  snuids-radar-panel
      - GF_AUTH_DISABLE_LOGIN_FORM=false
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ORG_NAME=Main Org.
      - GF_SERVER_ROOT_URL=http://localhost:3000
      - GF_DATABASE_HOST=influxdb:8086
      - GF_DATABASE_PORT=8086
      - GF_DATABASE_NAME=grafana
      - GF_DATABASE_USER=admin
      - GF_DATABASE_PASSWORD=pass


volumes:
  influxdb_data:
networks:
  socaNet:
